name: app_main
description: "NantoNack メインアプリ"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.3

resolution: workspace

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  quiz_core:
    path: ../../packages/quiz_core
  responsive_framework: ^1.5.1
  shopping:
    path: ../../packages/quizzes/shopping
  slang_flutter: ^4.3.1
  system:
    path: ../../packages/system

dev_dependencies:
  alchemist: ^0.14.0
  altive_lints: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
