name: system
description: "NantoNack 基盤パッケージ (Firebase, Drift, IAP)"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.3

resolution: workspace

dependencies:
  clock: ^1.1.2
  drift: ^2.22.1
  envied: ^1.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  logger: ^2.6.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.29

dev_dependencies:
  altive_lints: ^2.2.0
  build_runner: ^2.4.15
  drift_dev: ^2.22.1
  envied_generator: ^1.3.3
  flutter_test:
    sdk: flutter
